/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cooklang_jni_Parser */

#ifndef _Included_org_cooklang_jni_Parser
#define _Included_org_cooklang_jni_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cooklang_jni_Parser
 * Method:    parse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cooklang_jni_Parser_parse
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
