/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cooklang_Parser */

#ifndef _Included_org_cooklang_Parser
#define _Included_org_cooklang_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cooklang_Parser
 * Method:    parseRecipe
 * Signature: (Ljava/lang/String;)Lorg/cooklang/Recipe;
 */
JNIEXPORT jobject JNICALL Java_org_cooklang_parser_Parser_parseRecipe
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
